# Generated by Django 6.0.3 on 2026-03-18 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('Primary', 'Primary'), ('Sub-Group', 'Sub-Group')], default='Primary', max_length=20)),
                ('nature', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.accountgroup')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=30)),
                ('voucher_type', models.CharField(choices=[('Journal', 'Journal'), ('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Contra', 'Contra'), ('Sales', 'Sales'), ('Purchase', 'Purchase')], default='Journal', max_length=20)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('company', 'voucher_number')},
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], default='Dr', max_length=2)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_balance_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], default='Dr', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='company.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounts.accountgroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'ledger_id')},
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.journalentry')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounts.ledger')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
